# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 06:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 27, 6, 12, 58, 649850, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
