# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0002_auto_20151227_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Product')),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='SalesOrder',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='restaurant',
            new_name='restaurantID',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer',
            new_name='customerID',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='userID',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.AddField(
            model_name='salesorder_product',
            name='salesOrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.SalesOrder'),
        ),
        migrations.AddField(
            model_name='customer_restaurant',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Customer'),
        ),
        migrations.AddField(
            model_name='customer_restaurant',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Restaurant'),
        ),
    ]
