# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0003_auto_20151228_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Product')),
                ('PurchaseOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Product')),
                ('vendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Vendor'),
        ),
    ]
