# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0004_auto_20151228_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
