# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0005_productinventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder_product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
