# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0006_purchaseorder_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 28, 1, 37, 14, 231021, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
