# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0007_purchaseorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchasePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='salesPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
