# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0008_auto_20151228_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductInventoryID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softecApp.ProductInventory'),
            preserve_default=False,
        ),
    ]
