# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0009_product_productinventoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softecApp.Product', unique=True),
        ),
    ]
