# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0011_auto_20151228_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductInventoryID',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='productID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProductInventoryID', to='softecApp.Product'),
        ),
    ]
