# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0012_auto_20151228_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_restaurant',
            old_name='RestaurantID',
            new_name='cestaurantID',
        ),
        migrations.RenameField(
            model_name='customer_restaurant',
            old_name='CustomerID',
            new_name='customerID',
        ),
        migrations.RenameField(
            model_name='purchaseorder_product',
            old_name='ProductID',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='purchaseorder_product',
            old_name='PurchaseOrderID',
            new_name='purchaseOrderID',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='productID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productInventoryID', to='softecApp.Product'),
        ),
    ]
