# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softecApp', '0013_auto_20151228_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderSubmittedDate', models.DateTimeField()),
                ('orderPaidDate', models.DateTimeField()),
                ('orderDueDate', models.DateField()),
                ('purchaseOrderID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrderInvoiceID', to='softecApp.PurchaseOrder')),
            ],
        ),
    ]
